# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Drink Item

# Model Form Field configuration
form: $/stone/foodmenu/models/drinkitem/fields.yaml

# Model Class name
modelClass: Stone\FoodMenu\Models\DrinkItem

# Default redirect location
defaultRedirect: stone/foodmenu/drinkitems

# Create page
create:
    title: Create Drink Item
    redirect: stone/foodmenu/drinkitems/update/:id
    redirectClose: stone/foodmenu/drinkitems

# Update page
update:
    title: Edit Drink Item
    redirect: stone/foodmenu/drinkitems
    redirectClose: stone/foodmenu/drinkitems

# Preview page
preview:
    title: Preview Drink Item