# ===================================
#  Relation Behavior Config
# ===================================

food_categories:
    label: Food Categories
    view:
        list: ~/plugins/stone/foodmenu/models/foodcategory/columns.yaml
        toolbarButtons: add|remove
    manage:
        list: ~/plugins/stone/foodmenu/models/foodcategory/columns.yaml
        form: ~/plugins/stone/foodmenu/models/foodcategory/fields.yaml

sub_categories:
    label: Food Sub Categories
    view:
        list: ~/plugins/stone/foodmenu/models/foodsubcategory/columns.yaml
        toolbarButtons: add|remove
    manage:
        list: ~/plugins/stone/foodmenu/models/foodsubcategory/columns.yaml
        form: ~/plugins/stone/foodmenu/models/foodsubcategory/fields.yaml